import os
import rtconfig
from building import *

Import('SDK_LIB')

cwd = GetCurrentDir()

# add general drivers
src = []
path =  [cwd]
src += Glob('HAL.cpp')

# add button hal
src += Glob('HAL_Button.cpp')

#add lcd hal
if GetDepend(['BSP_USING_ONBOARD_LCD']):
    src += Glob('HAL_LCD.cpp')

#add rtc hal
if GetDepend(['BSP_USING_ONCHIP_RTC']):
    src += Glob('HAL_RTC.cpp')

#add sd hal
if GetDepend(['BSP_USING_SDCARD_FATFS']):
    src += Glob('HAL_SDCard.cpp')

#add spi flash
if GetDepend(['BSP_USING_SPI_FLASH']):
    src += Glob('HAL_SPIFlash.cpp')
    

CPPDEFINES = ['STM32F407xx']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
