from building import *
import os
import rtconfig

cwd = GetCurrentDir()
group = []
src = Glob('*.cpp')
CPPPATH = [cwd]

if GetDepend(['PKG_USING_LVGL']):
    src += Glob('_Template/*.cpp')
    CPPPATH += [cwd + '/_Template']

    src += Glob('Dialplate/*.cpp')
    CPPPATH += [cwd + '/Dialplate']

    src += Glob('StartUp/*.cpp')
    CPPPATH += [cwd + '/StartUp']

    src += Glob('SystemInfos/*.cpp')
    CPPPATH += [cwd + '/SystemInfos']

if GetDepend(['BSP_USING_ONBOARD_LCD']):
    src += Glob('Reader/*.cpp')
    CPPPATH += [cwd + '/Reader']

list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))

group = group + DefineGroup('Pages', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
