from building import *
import os
import rtconfig

cwd = GetCurrentDir()
group = []
src = Glob('*.cpp')
CPPPATH = [cwd]

src += Glob('_Template/*.cpp')
CPPPATH += [cwd + '/_Template']

src += Glob('Dial/*.cpp')
CPPPATH += [cwd + '/Dial']

src += Glob('StartUp/*.cpp')
CPPPATH += [cwd + '/StartUp']

src += Glob('SysInfos/*.cpp')
CPPPATH += [cwd + '/SysInfos']

list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))

group = group + DefineGroup('Pages', src, depend = ['PKG_USING_LVGL'], CPPPATH = CPPPATH)

Return('group')
