from building import *
import os
import rtconfig

cwd = GetCurrentDir()
group = []
src = Glob('Reader.cpp')
CPPPATH = [cwd]


list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))

group = group + DefineGroup('Reader', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
