from building import *
import os
import rtconfig

cwd = GetCurrentDir()
group = []
src = Glob('*.c')
src += Glob('*.cpp')
CPPPATH = [cwd]

list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))

group = group + DefineGroup('Pages', src, depend = ['PKG_USING_LVGL'], CPPPATH = CPPPATH)

Return('group')
