from building import *
import os
import rtconfig

cwd = GetCurrentDir()
group = []
src = Glob('Reader.cpp')
CPPPATH = [cwd]

group = group + DefineGroup('Reader', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
