import os
import rtconfig
from building import *

Import('SDK_LIB')

cwd = GetCurrentDir()

# add general drivers
src = []
path =  [cwd]

src += Glob('*.c')

#add lcd driver
if GetDepend(['BSP_USING_SRAM']):
    src += Glob('drv_sram.c')
    
if GetDepend(['BSP_USING_ONBOARD_LCD']):
    src += Glob('LCD_ST7789/Drv_ST7789.c')
    path += [cwd + '/LCD_ST7789']
    
if GetDepend(['BSP_USING_FS']):
    src += Glob('Drv_FileSystem.c')

CPPDEFINES = ['STM32F407xx']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
