import os
import rtconfig
from building import *

Import('SDK_LIB')

cwd = GetCurrentDir()

# add general drivers
src = []
path =  [cwd]

src += Glob('*.c')

#add MultiButton lib
src += Glob('MultiButton/MultiButton.c')
path += [cwd + '/MultiButton']

#add lcd module
if GetDepend(['BSP_USING_SRAM']):
    src += Glob('drv_sram.c')
    
if GetDepend(['BSP_USING_ONBOARD_LCD']):
    src += Glob('LCD_ST7789/Drv_ST7789.c')
    path += [cwd + '/LCD_ST7789']

# File System
if GetDepend(['BSP_USING_FS']):
    src += Glob('Drv_FileSystem.c')

# NorFlash W25Q64
if GetDepend(['BSP_USING_SPI_FLASH']):
    src += Glob('SPIFlash_W25Q64/*.c')
    path += [cwd + '/SPIFlash_W25Q64']

# Flash Abstract Layer
if GetDepend(['BSP_USING_FAL']):
    src += Glob('fal/*.c')
    path += [cwd + '/fal']

# EasyFlash
if GetDepend(['BSP_USING_EASYFLASH']):
    src += Glob('easyflash/*.c')
    path += [cwd + '/easyflash']

#add audio module
if GetDepend(['BSP_USING_AUDIO']):
    src += Glob('Audio_ES8388/drv_es8388.c')
    src += Glob('Audio_ES8388/drv_sound.c')
    path += [cwd + '/Audio_ES8388']

if GetDepend(['BSP_USING_AUDIO_RECORD']):
    src += Glob('Audio_ES8388/drv_mic.c')

CPPDEFINES = ['STM32F407xx']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
